apiVersion: v1
kind: Namespace
metadata:
  name: game-2048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
  namespace: game-2048
spec:
  selector:
    matchLabels:
      app: "2048"
  replicas: 5
  template:
    metadata:
      labels:
        app: "2048"
    spec:
      containers:
        - image: alexwhen/docker-2048
          imagePullPolicy: Always
          name: "2048"
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: game-2048
  namespace: game-2048
  labels:
    app: servicelabel
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: "2048"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-2048
  namespace: game-2048
  annotations:
    cert-manager.io/cluster-issuer: "vault-issuer"
    cert-manager.io/common-name: "game.127.0.0.1.nip.io"  
spec:
  ingressClassName: nginx
  rules:
  - host: game.127.0.0.1.nip.io
    http:
      paths:
      - backend:
          service:
            name: game-2048
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - game.127.0.0.1.nip.io
    secretName: game.127.0.0.1.nip.io
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: vault-cert
#   namespace: game-2048
# spec:
#   secretName: game.127.0.0.1.nip.io
#   issuerRef:
#     name: vault-issuer
#     kind: ClusterIssuer
#   commonName: "game.127.0.0.1.nip.io"
#   dnsNames:
#   - "game.127.0.0.1.nip.io"
